spring.application.name=api

# Change
spring.datasource.url=jdbc:postgresql://localhost:5432/projectNI
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

api.security.token.secret=your-very-strong-and-secret-key-here

logging.level.org.springframework.security=DEBUG